version: '3.3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: blog/app
        container_name: blog
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - ./src:/var/www
            - ./resources/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - db
            - webserver
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./src:/var/www
            - ./resources/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:8.0.4
        container_name: blog_mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: blog
            MYSQL_ROOT_PASSWORD: testpass
            MYSQL_USER: testuser
            MYSQL_PASS: myuserpass
            #MYSQL_PASSWORD_FILE: /run/secrets/db_password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./resources/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

# Docker Networks
networks:
    app-network:
        driver: bridge
# Volumes
volumes:
    dbdata:
        driver: local
# Secrets
secrets:
    db_root_password:
        file: db_root_password.txt
    db_password:
        file: db_password.txt
